export const PILLS_ACTION_TYPES = {
	SET_PILLS_CATEGORIES: "pills/SET_PILLS_CATEGORIES",
	SET_SELECTED_CATEGORY: "SET_SELECTED_CATEGORY",
	SET_CATEGORY: "SET_CATEGORY",
	SET_SELECTED_PILL: "SET_SELECTED_PILL",
	CATEGORY_CSS: "CSS",
	CATEGORY_JAVASCRIPT: "JAVASCRIPT",
	CATEGORY_REACT: "REACT",
};
